const restaurantList = [
  {
    info: {
      id: "1135383",
      name: "Rice Bowl",
      cloudinaryImageId: "cgkenu9elejxh8x5l1wq",
      locality: "Himayath Nagar",
      areaName: "Himayath Nagar",
      costForTwo: "₹450 for two",
      cuisines: ["South Indian"],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 33,
        slaString: "30-35 mins",
        lastMileTravelString: "4.9 km",
      },
    },
  },
  {
    info: {
      id: "603116",
      name: "Barbeque Nation",
      cloudinaryImageId: "az9ex7bhar9uwg5yhcdm",
      locality: "City Plaza",
      areaName: "ABIDS",
      costForTwo: "₹600 for two",
      cuisines: [
        "North Indian",
        "Barbecue",
        "Kebabs",
        "Biryani",
        "Street Food",
        "Snacks",
      ],
      avgRating: 3.7,
      veg: false,
      sla: {
        deliveryTime: 39,
        slaString: "35-40 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "1535",
      name: "Paradise Biryani",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/3/26/fcdfc743-5641-44c0-a39d-218df4738545_1535.JPG",
      locality: "Masab Tank",
      areaName: "Masab Tank",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "Kebabs", "North Indian", "Hyderabadi"],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 37,
        slaString: "35-40 mins",
        lastMileTravelString: "4.1 km",
      },
    },
  },
  {
    info: {
      id: "1312299",
      name: "GharSe - Homestyle & Healthy Tiffins",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/3/24/68e57ca1-0ecd-484b-8e25-5839a35567a0_1312299.JPG",
      locality: "GUDIMAKAPUR",
      areaName: "Mehdipatnam Circle No 12",
      costForTwo: "₹200 for two",
      cuisines: ["Biryani", "Thalis", "Home Food"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 25,
        slaString: "20-30 mins",
        lastMileTravelString: "3.9 km",
      },
    },
  },
  {
    info: {
      id: "142670",
      name: "Shah Ghouse Hotel & Restaurant",
      cloudinaryImageId: "grqh1zb1kv8uhkmyercb",
      locality: "Lakdi-Ka-Pul",
      areaName: "Banjara Hills",
      costForTwo: "₹350 for two",
      cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 68,
        slaString: "65-75 mins",
        lastMileTravelString: "3.8 km",
      },
    },
  },
  {
    info: {
      id: "1030896",
      name: "Thalaiva Biryani",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2026/5/14/56294d10-370a-4555-8681-b9f4e975f0d9_b853a651-81d7-4a9b-837e-7aed124b0a33.jpeg",
      locality: "Beside Little Flower Primary school",
      areaName: "Abids",
      costForTwo: "₹400 for two",
      cuisines: [
        "Biryani",
        "Mughlai",
        "Lucknowi",
        "Hyderabadi",
        "Kebabs",
        "Desserts",
        "Beverages",
      ],
      avgRating: 3.8,
      veg: false,
      sla: {
        deliveryTime: 34,
        slaString: "30-40 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "1350119",
      name: "Leon's - Burgers & Wings (Leon Grill)",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/5/26/584a5f32-20cf-42bf-b4ad-4756ebf468b2_01dc9e95-15f4-4e6f-a4a2-3930bf9d9e50.jpeg",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: [
        "American",
        "Turkish",
        "Fast Food",
        "Biryani",
        "South Indian",
        "Indian",
      ],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 47,
        slaString: "45-50 mins",
        lastMileTravelString: "7.9 km",
      },
    },
  },
  {
    info: {
      id: "414835",
      name: "Pizza Hut",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/6/15/33797bda-2361-4c05-a52e-f862567c6cac_414835.JPG",
      locality: "Khairatabad",
      areaName: "Khairatabad",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 41,
        slaString: "40-50 mins",
        lastMileTravelString: "4.8 km",
      },
    },
  },
  {
    info: {
      id: "1270243",
      name: "Chinese Wok",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/24/77db753c-a099-43e9-818a-aa523659a8a4_1270243.JPG",
      locality: "Amberpet Circle no 16",
      areaName: "Next Galleria Moosarambagh Mall",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      avgRating: 3.9,
      veg: false,
      sla: {
        deliveryTime: 47,
        slaString: "45-55 mins",
        lastMileTravelString: "7.0 km",
      },
    },
  },
  {
    info: {
      id: "77671",
      name: "Homely",
      cloudinaryImageId: "wp2byr5zax7bic6bu6dc",
      locality: "Banjarahills",
      areaName: "Banjarahills",
      costForTwo: "₹200 for two",
      cuisines: [
        "Home Food",
        "North Indian",
        "South Indian",
        "Beverages",
        "Desserts",
        "Thalis",
      ],
      avgRating: 4,
      veg: true,
      sla: {
        deliveryTime: 49,
        slaString: "45-55 mins",
        lastMileTravelString: "6.7 km",
      },
    },
  },
  {
    info: {
      id: "1022488",
      name: "Raju Gari Biryani",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/1/7/37aaa781-d4b8-4c0d-b390-3c5450a66338_1022488.jpg",
      locality: "Nallakunta & Vidyanagar",
      areaName: "Nallakunta & Vidyanagar",
      costForTwo: "₹300 for two",
      cuisines: ["Biryani"],
      avgRating: 3.8,
      veg: false,
      sla: {
        deliveryTime: 32,
        slaString: "30-40 mins",
        lastMileTravelString: "7.8 km",
      },
    },
  },
  {
    info: {
      id: "1054255",
      name: "Dabba & Co.",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/19/012c8da1-731a-4016-aa52-01fd77b1bb80_1054255.jpg",
      locality: "Beside Little Flower Primary school",
      areaName: "Abids",
      costForTwo: "₹200 for two",
      cuisines: ["Home food", "Indian", "Thalis"],
      avgRating: 3.9,
      veg: true,
      sla: {
        deliveryTime: 32,
        slaString: "30-40 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "1076630",
      name: "ITC Aashirvaad Soul Creations",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/3/30/81b027bc-b7cb-4d7e-a21e-beadd6cf6992_1076630.JPG",
      locality: "Mehdipatnam Road",
      areaName: "Mehdipatnam",
      costForTwo: "₹500 for two",
      cuisines: [
        "Indian",
        "pure veg",
        "Healthy Food",
        "Home Food",
        "South Indian",
        "North Indian",
        "Sweets",
      ],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 28,
        slaString: "25-30 mins",
        lastMileTravelString: "4.1 km",
      },
    },
  },
  {
    info: {
      id: "792059",
      name: "California Burrito",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/9/3/86f01901-5a7f-4292-b314-9e67e6404f58_792059.jpg",
      locality: "Burrito Restaurants",
      areaName: "Himayath Nagar",
      costForTwo: "₹250 for two",
      cuisines: [
        "Mexican",
        "American",
        "Salads",
        "Continental",
        "Keto",
        "Healthy Food",
        "Beverages",
        "Snacks",
        "Desserts",
        "Fast Food",
      ],
      avgRating: 4.6,
      veg: false,
      sla: {
        deliveryTime: 31,
        slaString: "30-35 mins",
        lastMileTravelString: "4.8 km",
      },
    },
  },
  {
    info: {
      id: "300363",
      name: "Barbeque Nation",
      cloudinaryImageId: "fb3b8wkhcnluea9hlshv",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹600 for two",
      cuisines: [
        "North Indian",
        "Barbecue",
        "Kebabs",
        "Biryani",
        "Street Food",
        "Snacks",
      ],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 62,
        slaString: "60-70 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "367769",
      name: "Lucky Restaurant",
      cloudinaryImageId: "qems028i3da5rxf81rbp",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: ["Biryani", "Tandoor"],
      avgRating: 4,
      veg: false,
      sla: {
        deliveryTime: 36,
        slaString: "35-40 mins",
        lastMileTravelString: "3.7 km",
      },
    },
  },
  {
    info: {
      id: "262087",
      name: "Imperial Multicuisine Restaurant",
      cloudinaryImageId: "rqlwvsmzcfxbg9u6ajgm",
      locality: "Banjara Hills",
      areaName: "Redhills",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 36,
        slaString: "35-40 mins",
        lastMileTravelString: "2.7 km",
      },
    },
  },
  {
    info: {
      id: "639526",
      name: "Dum Safar Biryani",
      cloudinaryImageId: "1154cffac2453eb0bf7fdda7e5ea1659",
      locality: "City Plaza",
      areaName: "ABIDS",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Hyderabadi", "Kebabs", "North Indian", "barbeque"],
      avgRating: 3.6,
      veg: false,
      sla: {
        deliveryTime: 43,
        slaString: "40-50 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "3324",
      name: "Srikanya",
      cloudinaryImageId: "tw4ytwle8yommmgdy4b0",
      locality: "Somajiguda",
      areaName: "Panjagutta",
      costForTwo: "₹250 for two",
      cuisines: ["Biryani", "Andhra", "South Indian"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 50,
        slaString: "50-60 mins",
        lastMileTravelString: "6.5 km",
      },
    },
  },
  {
    info: {
      id: "355751",
      name: "Grameen Kulfi",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/17/09b8dfb1-8a49-47ea-a3d4-6ae62d2c7217_355751.JPG",
      locality: "Khairatabad",
      areaName: "Banjara Hills",
      costForTwo: "₹120 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.6,
      veg: true,
      sla: {
        deliveryTime: 49,
        slaString: "45-50 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "587477",
      name: "Harley's Fine Baking",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/4/13/e613d368-4382-446c-853e-e8a84b0d5932_587477.JPG",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹500 for two",
      cuisines: ["Desserts", "Fast Food", "Bakery", "Sweets", "Snacks"],
      avgRating: 4.6,
      veg: true,
      sla: {
        deliveryTime: 51,
        slaString: "50-60 mins",
        lastMileTravelString: "5.5 km",
      },
    },
  },
  {
    info: {
      id: "838833",
      name: "Wow! China",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/22/57499db2-b38f-4d77-bc95-3741e96ae74c_838833.JPG",
      locality: "Buddha Poornima Project Area",
      areaName: "Prasad Imax",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Asian", "fastfood", "Beverages", "Snacks"],
      avgRating: 3.9,
      veg: false,
      sla: {
        deliveryTime: 48,
        slaString: "45-50 mins",
        lastMileTravelString: "4.9 km",
      },
    },
  },
  {
    info: {
      id: "435640",
      name: "Bakingo",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/7/1/b60baef0-d171-4c74-a641-1d87c6b5e56c_435640.JPG",
      locality: "Khairtabad",
      areaName: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery"],
      avgRating: 4.6,
      veg: false,
      sla: {
        deliveryTime: 49,
        slaString: "45-50 mins",
        lastMileTravelString: "6.2 km",
      },
    },
  },
  {
    info: {
      id: "25251",
      name: "Meridian Restaurant",
      cloudinaryImageId: "cxvuxxwpkicbqo3nkqiy",
      locality: "Panjagutta",
      areaName: "Panjagutta",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "Chinese", "Kebabs"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 47,
        slaString: "45-50 mins",
        lastMileTravelString: "6.5 km",
      },
    },
  },
  {
    info: {
      id: "44119",
      name: "Baskin Robbins - Ice Cream Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/4/24/1a787057-6e1c-4fac-8969-78d748b20a87_44119.JPG",
      locality: "Masab Tank",
      areaName: "Masab Tank",
      costForTwo: "₹400 for two",
      cuisines: ["Ice Cream", "Beverages"],
      avgRating: 4.4,
      veg: true,
      sla: {
        deliveryTime: 38,
        slaString: "35-40 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "27739",
      name: "Cafe Niloufer Classic",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/2/20/756a4815-2e45-4a50-b91b-27f2d503d9ce_27739.jpg",
      locality: "Oshiwara",
      areaName: "Khairatabad",
      costForTwo: "₹150 for two",
      cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
      avgRating: 4.7,
      veg: false,
      sla: {
        deliveryTime: 39,
        slaString: "35-40 mins",
        lastMileTravelString: "2.8 km",
      },
    },
  },
  {
    info: {
      id: "837954",
      name: "The Pizza Project by Oven Story",
      cloudinaryImageId: "f1b907b0b8f86c62e4fc347c6b1434e6",
      locality: "Beside Little Flower Primary school",
      areaName: "Abids",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Desserts", "Beverages"],
      avgRating: 4.1,
      veg: false,
      sla: {
        deliveryTime: 47,
        slaString: "45-55 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "6498",
      name: "Hotel Sandarshini",
      cloudinaryImageId: "9f5783b9975a73ec001560327065a01c",
      locality: "Masab Tank",
      areaName: "Masab Tank",
      costForTwo: "₹200 for two",
      cuisines: ["Chinese", "South Indian", "Juices", "North Indian"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 42,
        slaString: "40-45 mins",
        lastMileTravelString: "3.8 km",
      },
    },
  },
  {
    info: {
      id: "185544",
      name: "NIC Ice Creams",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/4/22/4fdaf481-0adf-4b5a-92bf-e9d2babc0191_185544.JPG",
      locality: "Khairatabad",
      areaName: "Banjara Hills",
      costForTwo: "₹120 for two",
      cuisines: ["Desserts", "Ice Cream"],
      avgRating: 4.6,
      veg: true,
      sla: {
        deliveryTime: 50,
        slaString: "45-50 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "376914",
      name: "Theobroma",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/6/25/17778651-9161-4cb0-89fa-0df920597d7a_376914.JPG",
      locality: "Somajiguda",
      areaName: "Somajiguda",
      costForTwo: "₹400 for two",
      cuisines: ["Desserts"],
      avgRating: 4.5,
      veg: false,
      sla: {
        deliveryTime: 44,
        slaString: "40-45 mins",
        lastMileTravelString: "6.2 km",
      },
    },
  },
  {
    info: {
      id: "110751",
      name: "Sri Balaji Mithai Bhandar",
      cloudinaryImageId: "ggcqycqkbqsdxkm9klot",
      locality: "SAIFABAD",
      areaName: "Masab tank",
      costForTwo: "₹300 for two",
      cuisines: ["Sweets", "Desserts", "Beverages"],
      avgRating: 4.4,
      veg: true,
      sla: {
        deliveryTime: 50,
        slaString: "50-60 mins",
        lastMileTravelString: "4.5 km",
      },
    },
  },
  {
    info: {
      id: "1111967",
      name: "Mealy - Your Everyday Meal",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/5/93d2737a-60c7-49b9-8f64-3ec23b10485f_1111967.jpg",
      locality: "Banjarahills",
      areaName: "Banjarahills",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Beverages", "Street Food"],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 62,
        slaString: "60-70 mins",
        lastMileTravelString: "6.7 km",
      },
    },
  },
  {
    info: {
      id: "641908",
      name: "Wholesome Bowlsome by Potful",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/12/26/f32375e5-d9d7-4681-9f64-94bf1dc172fa_641908.jpg",
      locality: "Tivari bros sweets",
      areaName: "Banjara Hills",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "North Indian", "Punjabi", "South Indian"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 52,
        slaString: "50-60 mins",
        lastMileTravelString: "5.8 km",
      },
    },
  },
  {
    info: {
      id: "1341378",
      name: "Immy Roti Boti",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/2/28/b4377741-cad3-4897-8ee9-ac98e9b9afa0_1341378.jpg",
      locality: "Banjara Hills",
      areaName: "Nampally",
      costForTwo: "₹500 for two",
      cuisines: ["North Indian", "Biryani", "South Indian", "Indian"],
      avgRating: 4.4,
      veg: false,
      sla: {
        deliveryTime: 32,
        slaString: "30-35 mins",
        lastMileTravelString: "1.4 km",
      },
    },
  },
  {
    info: {
      id: "860356",
      name: "Madras Curd Rice Company",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/2/19/df981da8-546f-48eb-82d5-69d62dfa7237_4e653564-303f-49a6-b1db-28aec6dacc87.jpg_compressed",
      locality: "Zehra Nagar",
      areaName: "Banjara hills",
      costForTwo: "₹200 for two",
      cuisines: ["South Indian", "Indian"],
      avgRating: 4.1,
      veg: true,
      sla: {
        deliveryTime: 38,
        slaString: "35-40 mins",
        lastMileTravelString: "5.9 km",
      },
    },
  },
  {
    info: {
      id: "400603",
      name: "Millet Express",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/3/10/48ff68a6-2b92-408a-ad22-c96c07f30228_80fff8a0-99fa-43e6-98ca-08b0734d0a50.jpg_compressed",
      locality: "Road No 10",
      areaName: "Banjara hills",
      costForTwo: "₹200 for two",
      cuisines: ["Healthy Food", "South Indian"],
      avgRating: 4.4,
      veg: false,
      sla: {
        deliveryTime: 40,
        slaString: "35-40 mins",
        lastMileTravelString: "5.9 km",
      },
    },
  },
  {
    info: {
      id: "964198",
      name: "Shero Home Food - Chettinad",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/5/8927ba5c-9c15-4964-bed1-9c74289e8beb_964198.jpg",
      locality: "JUDGES COLONY",
      areaName: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: [
        "Home Food",
        "Chettinad",
        "South Indian",
        "healthy",
        "dessert",
        "Snacks",
        "North Indian",
      ],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 45,
        slaString: "40-45 mins",
        lastMileTravelString: "2.3 km",
      },
    },
  },
  {
    info: {
      id: "870101",
      name: "Arambam - Flavours of South",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/11/28/b471b560-bf27-4005-b8d8-c6175df13fe7_74b7715b-76cc-4147-9ee0-c8a257d65033.png_compressed",
      locality: "Zehra Nagar",
      areaName: "Banjara hills",
      costForTwo: "₹200 for two",
      cuisines: ["South Indian", "Healthy Food"],
      avgRating: 4.1,
      veg: true,
      sla: {
        deliveryTime: 42,
        slaString: "40-50 mins",
        lastMileTravelString: "5.9 km",
      },
    },
  },
  {
    info: {
      id: "4810",
      name: "Hotel Sitara Grand - Dhanturi Group of hotels",
      cloudinaryImageId: "wc1ofefdkj9psnfytbmh",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: ["Biryani", "Chinese", "South Indian", "Tandoor"],
      avgRating: 4.1,
      veg: false,
      sla: {
        deliveryTime: 45,
        slaString: "40-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "67791",
      name: "Rambharose - Bhattad Ki Idli",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/8/13/538763bd-8b40-4ed6-8e4f-dd337c3a8017_24f3fdba-909c-414c-beea-ac6c56ad8efd.jpg",
      locality: "Narayanguda Rd",
      areaName: "Kachiguda",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "Breakfast"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 41,
        slaString: "40-45 mins",
        lastMileTravelString: "5.5 km",
      },
    },
  },
  {
    info: {
      id: "11854",
      name: "Taj Mahal Hotel",
      cloudinaryImageId: "cjpiqvhb53emmrcm2tyr",
      locality: "Himayath Nagar",
      areaName: "Himayath Nagar",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Chinese", "South Indian", "Tandoor"],
      avgRating: 4.6,
      veg: true,
      sla: {
        deliveryTime: 45,
        slaString: "40-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "370144",
      name: "Patel's Delights",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2026/2/12/c7d92197-1159-4aa7-a6eb-c0d98c0fe99f_7e381dd4-129d-412a-9d75-c002d0412e5d.jpg",
      locality: "Amberpet Circle No 16",
      areaName: "Kachiguda Hyderabad",
      costForTwo: "₹350 for two",
      cuisines: ["Indian", "Snacks", "Sweets", "Street Food"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 42,
        slaString: "40-45 mins",
        lastMileTravelString: "6.2 km",
      },
    },
  },
  {
    info: {
      id: "588594",
      name: "Swaad of South",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/10/30/060b6801-dcf3-4c8b-bb52-ab8060a89c1b_c52e28ec-3efb-4ce4-b7f6-532fa0394443.jpg",
      locality: "Basheerbagh",
      areaName: "Basheerbagh",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "North Indian", "Chinese"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 37,
        slaString: "35-40 mins",
        lastMileTravelString: "4.8 km",
      },
    },
  },
  {
    info: {
      id: "496680",
      name: "Shree Golden Palace Restaurant",
      cloudinaryImageId: "gqpiulg3sjg5hn3ohtjq",
      locality: "Guddimalkapur",
      areaName: "Gudimalkapur",
      costForTwo: "₹250 for two",
      cuisines: ["briyani", "South Indian", "Indian", "North Indian"],
      avgRating: 4.1,
      veg: false,
      sla: {
        deliveryTime: 45,
        slaString: "40-50 mins",
        lastMileTravelString: "4.4 km",
      },
    },
  },
  {
    info: {
      id: "711834",
      name: "Rollsking",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/5/29/d070e908-744c-468f-9481-cc434461e638_f5ee620f-4cb0-46e6-9ca7-620d20854f97.jpg",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹500 for two",
      cuisines: [
        "Rolls & Wraps",
        "Fast Food",
        "Snacks",
        "Beverages",
        "North Indian",
      ],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 43,
        slaString: "40-45 mins",
        lastMileTravelString: "7.1 km",
      },
    },
  },
  {
    info: {
      id: "35489",
      name: "Zomoz - The Momo Company",
      cloudinaryImageId: "pzudmwbzerpxjblwqp9g",
      locality: "Sagar Ring Road",
      areaName: "Masab Tank",
      costForTwo: "₹250 for two",
      cuisines: ["Momos", "Chinese"],
      avgRating: 4.1,
      veg: false,
      sla: {
        deliveryTime: 37,
        slaString: "35-40 mins",
        lastMileTravelString: "3.9 km",
      },
    },
  },
  {
    info: {
      id: "74341",
      name: "Amantran Bengali Restaurant",
      cloudinaryImageId: "dxr03njc4wfuedfv3wxk",
      locality: "Panjagutta",
      areaName: "Banjara Hills",
      costForTwo: "₹200 for two",
      cuisines: ["Bengali", "North Indian", "Home Food", "Thalis", "Beverages"],
      avgRating: 4,
      veg: false,
      sla: {
        deliveryTime: 51,
        slaString: "50-60 mins",
        lastMileTravelString: "6.0 km",
      },
    },
  },
  {
    info: {
      id: "324333",
      name: "The Nosh Bistro",
      cloudinaryImageId: "ytmmqrwh8mygjwt6y6d4",
      locality: "Himayath Nagar",
      areaName: "Himayath Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Continental", "Pizzas", "Momos"],
      avgRating: 4.3,
      veg: true,
      sla: {
        deliveryTime: 43,
        slaString: "40-50 mins",
        lastMileTravelString: "5.6 km",
      },
    },
  },
  {
    info: {
      id: "35008",
      name: "Alex's Kitchen",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2026/1/9/5e6c6a64-1704-42ad-b367-7ba8dc465746_673ae961-314f-4a07-a8e2-d6393697f7ab.JPG",
      locality: "Himayat Nagar",
      areaName: "Himayath Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Asian", "Seafood", "Tibetan", "Fast Food"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 39,
        slaString: "35-40 mins",
        lastMileTravelString: "4.5 km",
      },
    },
  },
  {
    info: {
      id: "43619",
      name: "Chung Hua Restaurant",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/9/16/98e746f6-14c7-4b62-8908-b0606e2359f5_69498761-e701-473e-925a-5e2637e045b3.jpg",
      locality: "Basheerbagh",
      areaName: "Basheerbagh",
      costForTwo: "₹300 for two",
      cuisines: [
        "Chinese",
        "Asian",
        "Thai",
        "Seafood",
        "Singaporean",
        "Malaysian",
      ],
      avgRating: 4.4,
      veg: false,
      sla: {
        deliveryTime: 46,
        slaString: "45-55 mins",
        lastMileTravelString: "4.4 km",
      },
    },
  },
  {
    info: {
      id: "940675",
      name: "Ta.Ma.Sha Veg Cafe",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2026/1/29/7f8dc358-d763-4b10-b89b-091e3dc4ecd5_05c473e4-201f-403c-9831-c0cc64141da1.JPG",
      locality: "Himayath Nagar",
      areaName: "Abids",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas", "Cafe"],
      avgRating: 3.9,
      veg: true,
      sla: {
        deliveryTime: 36,
        slaString: "35-40 mins",
        lastMileTravelString: "3.5 km",
      },
    },
  },
  {
    info: {
      id: "52015",
      name: "D-Lite Frankie",
      cloudinaryImageId: "04dc5aff47957c7c4baaba761a469660",
      locality: "Zahara nagar",
      areaName: "Banjara Hills",
      costForTwo: "₹200 for two",
      cuisines: ["Indian", "Rolls & Wraps"],
      avgRating: 3.8,
      veg: false,
      sla: {
        deliveryTime: 47,
        slaString: "45-55 mins",
        lastMileTravelString: "4.6 km",
      },
    },
  },
  {
    info: {
      id: "1005081",
      name: "Boba Bhai - Bubble Tea & Korean Street Food",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/8/18/afb5b85d-3970-4919-bc9a-3b3c4fa0b087_fba5788e-40b6-4bf7-81d1-b8956d3ad6a7.jpg_compressed",
      locality: "Mithali Nagar",
      areaName: "Banjara Hills",
      costForTwo: "₹200 for two",
      cuisines: [
        "Bubble Tea",
        "Burger",
        "Korean",
        "Beverages",
        "Fast Food",
        "Juice and shake",
      ],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 49,
        slaString: "45-50 mins",
        lastMileTravelString: "7.1 km",
      },
    },
  },
  {
    info: {
      id: "927258",
      name: "Italian Burrito",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/7/18/af9fe3e1-fd01-43d0-a452-320949dcb1fd_cebc9d10-b7a4-47e7-8564-db2b1927df49.jpg",
      locality: "Falaknuma ",
      areaName: "Charminar",
      costForTwo: "₹400 for two",
      cuisines: ["Italian", "Pizzas", "Burgers", "Snacks"],
      avgRating: 4.4,
      veg: false,
      sla: {
        deliveryTime: 54,
        slaString: "50-60 mins",
        lastMileTravelString: "6.8 km",
      },
    },
  },
  {
    info: {
      id: "150646",
      name: "Cream Stone Ice Cream",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/7/2/b1726181-d54b-469b-9a3a-33ed5596a68c_150646.JPG",
      locality: "Begum Bazaar",
      areaName: "Himayath Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["Ice Cream", "Desserts", "Beverages", "Ice Cream Cakes"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 38,
        slaString: "35-40 mins",
        lastMileTravelString: "3.9 km",
      },
    },
  },
  {
    info: {
      id: "1098942",
      name: "The Belgian Waffle Co.",
      cloudinaryImageId: "470cc03f5f2b98c2ca5dde4f71300f55",
      locality: "ABDULLAH COLONY",
      areaName: "MOZAMJAHI MARKET",
      costForTwo: "₹200 for two",
      cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
      avgRating: 4.6,
      veg: true,
      sla: {
        deliveryTime: 33,
        slaString: "30-35 mins",
        lastMileTravelString: "2.1 km",
      },
    },
  },
  {
    info: {
      id: "348662",
      name: "CakeZone Patisserie",
      cloudinaryImageId: "jludfnb5yex080yc2ruj",
      locality: "VITHALWADI",
      areaName: "Himayath Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 41,
        slaString: "40-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "1125685",
      name: "Cream Stone Tubz",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/6/25/206ba5b8-56d3-4125-87ab-060740df052f_54dbabac-2024-42d2-9fe3-4678dae84b3d.jpeg",
      locality: "Khairatabad Circle No.17",
      areaName: "Himayath Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 37,
        slaString: "35-40 mins",
        lastMileTravelString: "4.1 km",
      },
    },
  },
  {
    info: {
      id: "419971",
      name: "Kwality Wall's Ice Cream And More",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/6/13/a3682a44-140d-424f-bba2-f02470f26d2b_419971.JPG",
      locality: "LAKDI KA POOL",
      areaName: "Khairtabad",
      costForTwo: "₹300 for two",
      cuisines: ["Ice Cream"],
      avgRating: 4.3,
      veg: true,
      sla: {
        deliveryTime: 34,
        slaString: "30-35 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "22948",
      name: "Makers of Milkshakes",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/6/26/54c019e1-d654-4766-9aec-4b7ab26476dd_af7cf6b2-b952-412b-916f-fb8636646819.jpg",
      locality: "King Koti Road",
      areaName: "King Koti",
      costForTwo: "₹260 for two",
      cuisines: ["Beverages", "Desserts", "Ice Cream"],
      avgRating: 4.2,
      veg: true,
      sla: {
        deliveryTime: 30,
        slaString: "30-35 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "898851",
      name: "Havmor Havfunn Ice Cream",
      cloudinaryImageId: "kzjspy62obsk8yx8gawf",
      locality: "Jawahar Nagar",
      areaName: "Nallakunta & Vidyanagar",
      costForTwo: "₹350 for two",
      cuisines: ["Ice Cream", "Cakes", "Desserts", "Beverages"],
      avgRating: 4.1,
      veg: true,
      sla: {
        deliveryTime: 47,
        slaString: "45-50 mins",
        lastMileTravelString: "6.7 km",
      },
    },
  },
  {
    info: {
      id: "690939",
      name: "Ovenfresh Cakes And Desserts",
      cloudinaryImageId: "1169accdd25a6bc7b0591110ec758b5d",
      locality: "Vithalwadi",
      areaName: "Himayath Nagar",
      costForTwo: "₹200 for two",
      cuisines: [
        "Bakery",
        "Desserts",
        "Beverages",
        "Ice Cream",
        "Sweets",
        "Juices",
        "Bengali",
        "Pizzas",
      ],
      avgRating: 4.2,
      veg: false,
      sla: {
        deliveryTime: 38,
        slaString: "35-40 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "442889",
      name: "The Dessert Heaven - Pastry, Brownie and Cakes",
      cloudinaryImageId: "cbwokvayrdfuhaes0pxr",
      locality: "Vithalwadi",
      areaName: "Himayath Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 38,
        slaString: "35-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "689081",
      name: "Third Wave Coffee",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2024/3/10/cb2243ad-5c8f-477a-849e-593703c08edd_3ed7e565-a2db-4e25-81fc-e4c7ce19cc4a_compressed",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹400 for two",
      cuisines: ["Beverages", "Cafe", "Desserts"],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 39,
        slaString: "35-40 mins",
        lastMileTravelString: "6.1 km",
      },
    },
  },
  {
    info: {
      id: "18012",
      name: "Cafe Coffee Day",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/8/21/a753556f-f367-42c5-a2f3-7b19a7ecffbe_18012.JPG",
      locality: "King Koti",
      areaName: "Basheerbagh",
      costForTwo: "₹400 for two",
      cuisines: [
        "Beverages",
        "Cafe",
        "Snacks",
        "Desserts",
        "Burgers",
        "Ice Cream",
        "Bakery",
        "Fast Food",
      ],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 42,
        slaString: "40-50 mins",
        lastMileTravelString: "4.8 km",
      },
    },
  },
  {
    info: {
      id: "721102",
      name: "Pista House Tea",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2025/2/19/ee092425-cd83-4196-93d4-b03983da6efb_62754de8-6373-4fcb-ac50-1788768bed72.png",
      locality: "King Kothi",
      areaName: "Abids & Koti",
      costForTwo: "₹500 for two",
      cuisines: ["Beverages", "Indian"],
      avgRating: 4.7,
      veg: false,
      sla: {
        deliveryTime: 34,
        slaString: "30-35 mins",
        lastMileTravelString: "4.2 km",
      },
    },
  },
  {
    info: {
      id: "662646",
      name: "Starbucks Coffee",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/5/4/f11bf9d3-2030-4587-9fff-b98b3af79c04_662646.JPG",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹400 for two",
      cuisines: [
        "Beverages",
        "Cafe",
        "Snacks",
        "Desserts",
        "Bakery",
        "Ice Cream",
      ],
      avgRating: 4.4,
      veg: false,
      sla: {
        deliveryTime: 40,
        slaString: "40-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
  {
    info: {
      id: "194562",
      name: "McCafe by McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/8/19/87e66ee6-c512-44ad-bdca-c62178e1a054_194562.jpg",
      locality: "ABITS MPM MALL",
      areaName: "Koti",
      costForTwo: "₹250 for two",
      cuisines: ["Beverages", "Desserts"],
      avgRating: 4.6,
      veg: false,
      sla: {
        deliveryTime: 40,
        slaString: "35-40 mins",
        lastMileTravelString: "4.1 km",
      },
    },
  },
  {
    info: {
      id: "440362",
      name: "Te - A Tea Tradition",
      cloudinaryImageId:
        "FOOD_CATALOG/IMAGES/CMS/2026/2/6/bb9668c4-341d-4f89-a7e3-c6d2bcae6ddb_4525f51a-33d3-4066-bbc0-4f038416bb9e.JPG",
      locality: "Opp to Balaji laxminarayan General Store",
      areaName: "Kachiguda",
      costForTwo: "₹150 for two",
      cuisines: ["Beverages", "Snacks"],
      avgRating: 4.5,
      veg: true,
      sla: {
        deliveryTime: 34,
        slaString: "30-35 mins",
        lastMileTravelString: "4.4 km",
      },
    },
  },
  {
    info: {
      id: "61315",
      name: "Chai Point",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/1/7/743ed112-22de-4d51-a9ca-39581dc04fdb_61315.JPG",
      locality: "Banjara Hills",
      areaName: "Banjara Hills",
      costForTwo: "₹150 for two",
      cuisines: [
        "Bakery",
        "Beverages",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "South Indian",
        "Punjabi",
        "Chaat",
        "Indian",
        "American",
      ],
      avgRating: 4.3,
      veg: false,
      sla: {
        deliveryTime: 41,
        slaString: "40-45 mins",
        lastMileTravelString: "5.0 km",
      },
    },
  },
];

export default restaurantList;
